/**
 * Stable, machine-readable error codes. Clients branch on `code`, never on `message`
 * (messages are Turkish, user-facing and may change).
 */
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Users & roles
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_CODE_TAKEN: 'ROLE_CODE_TAKEN',
  SYSTEM_ROLE_IMMUTABLE: 'SYSTEM_ROLE_IMMUTABLE',
  SELF_MODIFICATION_FORBIDDEN: 'SELF_MODIFICATION_FORBIDDEN',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT_NOT_FOUND',

  // Municipality domain
  MUNICIPALITY_NOT_FOUND: 'MUNICIPALITY_NOT_FOUND',
  DEPARTMENT_CODE_TAKEN: 'DEPARTMENT_CODE_TAKEN',
  DEPARTMENT_INACTIVE: 'DEPARTMENT_INACTIVE',
  DEPARTMENT_IN_USE: 'DEPARTMENT_IN_USE',
  NEIGHBORHOOD_NOT_FOUND: 'NEIGHBORHOOD_NOT_FOUND',
  NEIGHBORHOOD_CODE_TAKEN: 'NEIGHBORHOOD_CODE_TAKEN',
  INVALID_GEOMETRY: 'INVALID_GEOMETRY',
  NEIGHBORHOOD_BOUNDARY_OVERLAP: 'NEIGHBORHOOD_BOUNDARY_OVERLAP',
  NEIGHBORHOOD_IMPORT_FAILED: 'NEIGHBORHOOD_IMPORT_FAILED',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_CODE_TAKEN: 'CATEGORY_CODE_TAKEN',
  CATEGORY_HIERARCHY_INVALID: 'CATEGORY_HIERARCHY_INVALID',
  CATEGORY_DEPARTMENT_REQUIRED: 'CATEGORY_DEPARTMENT_REQUIRED',
  CATEGORY_PARENT_INACTIVE: 'CATEGORY_PARENT_INACTIVE',

  // Requests
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_CLOSED: 'REQUEST_CLOSED',
  CATEGORY_INACTIVE: 'CATEGORY_INACTIVE',
  CATEGORY_NOT_SELECTABLE: 'CATEGORY_NOT_SELECTABLE',
  CATEGORY_NOT_ROUTABLE: 'CATEGORY_NOT_ROUTABLE',
  TRANSITION_REASON_REQUIRED: 'TRANSITION_REASON_REQUIRED',
  MEDIA_LIMIT_REACHED: 'MEDIA_LIMIT_REACHED',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  INVALID_IMAGE: 'INVALID_IMAGE',
  IMAGE_DIMENSIONS_TOO_LARGE: 'IMAGE_DIMENSIONS_TOO_LARGE',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',

  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  WORK_ORDER_NOT_FOUND: 'WORK_ORDER_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
